---
output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  concurrency: 0
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  disable-all: false
  enable-all: true
  disable:
    # Opting-out
    - nonamedreturns  # named returns are occasionally useful
    - exhaustruct  # does not serve much of a purpose
    - funlen  # not interested
    - cyclop  # not interested much
    - godox  # having these are useful

    # Duplicating
    - gci  # we use go-imports instead

    # Deprecated
    - tenv

    # FIXME: under review
    - wrapcheck

linters-settings:
  staticcheck:
    checks:
      - "all"

  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - go.farcloser.world/core
          - go.farcloser.world/containers
          - gotest.tools/v3/assert
          - golang.org/x/sys/unix
          - golang.org/x/sys/windows
          - github.com/opencontainers/go-digest
          - github.com/opencontainers/image-spec
          - github.com/opencontainers/runtime-spec
          - github.com/containerd/containerd/v2
          - github.com/containerd/cgroups
          - github.com/distribution/reference
          - github.com/moby/sys/userns
          - github.com/vishvananda/netlink
          - github.com/vishvananda/netns
